export const FETCH_EVENTS_BEGIN = '@@tracker/FETCH_EVENTS_BEGIN'
export const FETCH_EVENTS_SUCCESS = '@@tracker/FETCH_EVENTS_SUCCESS'
export const FETCH_EVENTS_FAILURE = '@@tracker/FETCH_EVENTS_FAILURE'

export const UPDATE_EVENT_BEGIN = '@@tracker/UPDATE_EVENT_BEGIN'
export const UPDATE_EVENT_SUCCESS = '@@tracker/UPDATE_EVENT_SUCCESS'
export const UPDATE_EVENT_FAILURE = '@@tracker/UPDATE_EVENT_FAILURE'

export const CREATE_EVENT_BEGIN = '@@tracker/CREATE_EVENT_BEGIN'
export const CREATE_EVENT_SUCCESS = '@@tracker/CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAILURE = '@@tracker/CREATE_EVENT_FAILURE'

export const DELETE_EVENT_BEGIN = '@@tracker/DELETE_EVENT_BEGIN'
export const DELETE_EVENT_SUCCESS = '@@tracker/DELETE_EVENT_SUCCESS'
export const DELETE_EVENT_FAILURE = '@@tracker/DELETE_EVENT_FAILURE'

export const FETCH_PROJECTS_BEGIN = '@@tracker/FETCH_PROJECTS_BEGIN'
export const FETCH_PROJECTS_SUCCESS = '@@tracker/FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECTS_FAILURE = '@@tracker/FETCH_PROJECTS_FAILURE'

export const UPDATE_PROJECT_BEGIN = '@@tracker/UPDATE_PROJECT_BEGIN'
export const UPDATE_PROJECT_SUCCESS = '@@tracker/UPDATE_PROJECT_SUCCESS'
export const UPDATE_PROJECT_FAILURE = '@@tracker/UPDATE_PROJECT_FAILURE'

export const CREATE_PROJECT_BEGIN = '@@tracker/CREATE_PROJECT_BEGIN'
export const CREATE_PROJECT_SUCCESS = '@@tracker/CREATE_PROJECT_SUCCESS'
export const CREATE_PROJECT_FAILURE = '@@tracker/CREATE_PROJECT_FAILURE'

export const DELETE_PROJECT_BEGIN = '@@tracker/DELETE_PROJECT_BEGIN'
export const DELETE_PROJECT_SUCCESS = '@@tracker/DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAILURE = '@@tracker/DELETE_PROJECT_FAILURE'

export const FETCH_CLIENTS_BEGIN = '@@tracker/FETCH_CLIENTS_BEGIN'
export const FETCH_CLIENTS_SUCCESS = '@@tracker/FETCH_CLIENTS_SUCCESS'
export const FETCH_CLIENTS_FAILURE = '@@tracker/FETCH_CLIENTS_FAILURE'

export const UPDATE_CLIENT_BEGIN = '@@tracker/UPDATE_CLIENT_BEGIN'
export const UPDATE_CLIENT_SUCCESS = '@@tracker/UPDATE_CLIENT_SUCCESS'
export const UPDATE_CLIENT_FAILURE = '@@tracker/UPDATE_CLIENT_FAILURE'

export const CREATE_CLIENT_BEGIN = '@@tracker/CREATE_CLIENT_BEGIN'
export const CREATE_CLIENT_SUCCESS = '@@tracker/CREATE_CLIENT_SUCCESS'
export const CREATE_CLIENT_FAILURE = '@@tracker/CREATE_CLIENT_FAILURE'

export const DELETE_CLIENT_BEGIN = '@@tracker/DELETE_CLIENT_BEGIN'
export const DELETE_CLIENT_SUCCESS = '@@tracker/DELETE_CLIENT_SUCCESS'
export const DELETE_CLIENT_FAILURE = '@@tracker/DELETE_CLIENT_FAILURE'
