export const CREATE_NOTIFICATION_BEGIN = '@@notification/CREATE_NOTIFICATION_BEGIN';
export const CREATE_NOTIFICATION_SUCCESS = '@@notification/CREATE_NOTIFICATION_SUCCESS';
export const CREATE_NOTIFICATION_FAILURE = '@@notification/CREATE_NOTIFICATION_FAILURE';

export const READ_NOTIFICATION_BEGIN = '@@notification/READ_NOTIFICATION_BEGIN';
export const READ_NOTIFICATION_SUCCESS = '@@notification/READ_NOTIFICATION_SUCCESS';
export const READ_NOTIFICATION_FAILURE = '@@notification/READ_NOTIFICATION_FAILURE';

export const FETCH_NOTIFICATIONS_BEGIN = '@@notification/FETCH_NOTIFICATIONS_BEGIN';
export const FETCH_NOTIFICATIONS_SUCCESS = '@@notification/FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = '@@notification/FETCH_NOTIFICATIONS_FAILURE';

export const FETCH_NEXT_NOTIFICATIONS_BEGIN = '@@notification/FETCH_NEXT_NOTIFICATIONS_BEGIN';
export const FETCH_NEXT_NOTIFICATIONS_SUCCESS = '@@notification/FETCH_NEXT_NOTIFICATIONS_SUCCESS';
export const FETCH_NEXT_NOTIFICATIONS_FAILURE = '@@notification/FETCH_NEXT_NOTIFICATIONS_FAILURE';
