export const FETCH_WORKSPACES_BEGIN = '@@workspace/FETCH_WORKSPACES_BEGIN'
export const FETCH_WORKSPACES_SUCCESS = '@@workspace/FETCH_WORKSPACES_SUCCESS'
export const FETCH_WORKSPACES_FAILURE = '@@workspace/FETCH_WORKSPACES_FAILURE'

export const CREATE_WORKSPACE_BEGIN = '@@workspace/CREATE_WORKSPACE_BEGIN'
export const CREATE_WORKSPACE_SUCCESS = '@@workspace/CREATE_WORKSPACE_SUCCESS'
export const CREATE_WORKSPACE_FAILURE = '@@workspace/CREATE_WORKSPACE_FAILURE'

export const UPDATE_WORKSPACE_BEGIN = '@@workspace/UPDATE_WORKSPACE_BEGIN'
export const UPDATE_WORKSPACE_SUCCESS = '@@workspace/UPDATE_WORKSPACE_SUCCESS'
export const UPDATE_WORKSPACE_FAILURE = '@@workspace/UPDATE_WORKSPACE_FAILURE'

export const DELETE_WORKSPACE_BEGIN = '@@workspace/DELETE_WORKSPACE_BEGIN'
export const DELETE_WORKSPACE_SUCCESS = '@@workspace/DELETE_WORKSPACE_SUCCESS'
export const DELETE_WORKSPACE_FAILURE = '@@workspace/DELETE_WORKSPACE_FAILURE'

export const CREATE_WORKSPACE_USER_BEGIN = '@@workspace/CREATE_WORKSPACE_USER_BEGIN'
export const CREATE_WORKSPACE_USER_SUCCESS = '@@workspace/CREATE_WORKSPACE_USER_SUCCESS'
export const CREATE_WORKSPACE_USER_FAILURE = '@@workspace/CREATE_WORKSPACE_USER_FAILURE'

export const UPDATE_WORKSPACE_USER_BEGIN = '@@workspace/UPDATE_WORKSPACE_USER_BEGIN'
export const UPDATE_WORKSPACE_USER_SUCCESS = '@@workspace/UPDATE_WORKSPACE_USER_SUCCESS'
export const UPDATE_WORKSPACE_USER_FAILURE = '@@workspace/UPDATE_WORKSPACE_USER_FAILURE'

export const DELETE_WORKSPACE_USER_BEGIN = '@@workspace/DELETE_WORKSPACE_USER_BEGIN'
export const DELETE_WORKSPACE_USER_SUCCESS = '@@workspace/DELETE_WORKSPACE_USER_SUCCESS'
export const DELETE_WORKSPACE_USER_FAILURE = '@@workspace/DELETE_WORKSPACE_USER_FAILURE'

// USERS
export const FETCH_USERS_BEGIN = '@@workspace/FETCH_USERS_BEGIN'
export const FETCH_USERS_SUCCESS = '@@workspace/FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = '@@workspace/FETCH_USERS_FAILURE'

export const CREATE_USER_BEGIN = '@@workspace/CREATE_USER_BEGIN'
export const CREATE_USER_SUCCESS = '@@workspace/CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = '@@workspace/CREATE_USER_FAILURE'

export const UPDATE_USER_BEGIN = '@@workspace/UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = '@@workspace/UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = '@@workspace/UPDATE_USER_FAILURE'

export const DELETE_USER_BEGIN = '@@workspace/DELETE_USER_BEGIN'
export const DELETE_USER_SUCCESS = '@@workspace/DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = '@@workspace/DELETE_USER_FAILURE'
